# Generated by Django 6.0.4 on 2026-06-27 15:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_operational_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditoriajob',
            index=models.Index(fields=['status', 'finaliza_em'], name='audit_status_finish_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriajob',
            index=models.Index(fields=['-iniciado_em'], name='audit_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='auditorialeitorstatus',
            index=models.Index(fields=['status', 'antena'], name='audit_reader_status_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacaoinconsistencia',
            index=models.Index(fields=['resolvida', '-criado_em'], name='incons_open_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacaoinconsistencia',
            index=models.Index(fields=['resolvida', 'tipo', '-criado_em'], name='incons_open_type_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacaoinconsistencia',
            index=models.Index(fields=['item', '-criado_em'], name='incons_item_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='timelineevento',
            index=models.Index(fields=['tipo', '-criado_em'], name='timeline_type_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='timelineevento',
            index=models.Index(fields=['item', '-criado_em'], name='timeline_item_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='timelineevento',
            index=models.Index(fields=['usuario', '-criado_em'], name='timeline_user_recent_idx'),
        ),
    ]
